---

  - name: get the current release
    command: lsb_release -cs
    register: releasename

  - debug:
      msg: "The release is: {{ releasename }}"

  - name: apt update
    apt:
      update_cache: yes
      upgrade: dist
    become: yes
    become_method: sudo

  - name: install package over network tools
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
    become: yes
    become_method: sudo


  - name: get needed key for Docker
    shell: curl -L https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    become: yes
    become_method: sudo

  - name: get needed key for R
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: E298A3A825C0D65DFD57CBB651716619E084DAB9
    become: yes
    become_method: sudo

  - name: get needed key for virtualbox
    shell: https://www.virtualbox.org/download/oracle_vbox.asc | sudo apt-key add -
      state: present
    become: yes
    become_method: sudo

  - name: get needed key for chrome
    shell: curl -L https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      state: present
    become: yes
    become_method: sudo

  - name: add repo for docker
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ releasename.stdout }} stable
    become: yes
    become_method: sudo

  - name: add repo for chrome
    apt_repository:
      repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    become: yes
    become_method: sudo

  - name: add repo for R
    apt_repository:
      repo: deb https://cloud.r-project.org/bin/linux/ubuntu {{ releasename.stdout }}-cran35/
    become: yes
    become_method: sudo

  - name: add repo for virtualbox
    apt_repository:
      repo: deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian {{ releasename.stdout }} lsb_release -cs contrib
    become: yes
    become_method: sudo

  - name: add repo for ansible
    apt_repository:
      repo: ppa:ansible/ansible
    become: yes
    become_method: sudo

  - name: apt update
    apt:
      update_cache: yes
      upgrade: dist

# git needs to be installed to get this playbook,
# so you should set it up passwordless for private repos
# so that this will run without incident.
  - name: Install some key packages I use
    apt:
      name:
        - vim
        - gdebi-core
        - git
        - ansible
        - nautilus-dropbox
        - gnome-tweak-tool
        - gnome-shell-extensions
        - chrome-gnome-shell
        - python3-dev
        - virtualbox-6.0
        - r-base
        - google-chrome-stable
        - docker-ce
        - docker-compose
    become: yes
    become_method: sudo

  - name: Clone fzf package
    git:
      clone: yes
      repo: https://github.com/junegunn/fzf.git
      dest: ~/.fzf

  - name: Get dropbox started up. Will still need to login.
    command: dropbox start -i && dropbox autostart y

  - name: Create some directories
    file:
      state: directory
      mode: 0755
      path: "{{ item }}"
    with_items:
      - "{{ home }}/.vim/pack/features/start"
      - "{{ home }}/.vim/pack/codesyntax/start"
      - "{{ home }}/.vim/pack/colors/opt"
      - "{{ home }}/dev/javascript"
      - "{{ home }}/dev/javascript/react"
      - "{{ home }}/dev/ansible/kubernetes_cluster"
      - "{{ home }}/dev/shellscripts"
      - "{{ home }}/General_Notes"
      - "{{ home }}/Tutorial_Notes"

  - name: remove some directories
    file:
      state: absent
    with_items:
      - "{{ home }}/Documents"
      - "{{ home }}/Music"
      - "{{ home }}/Public"
      - "{{ home }}/Templates"
      - "{{ home }}/Videos"
      - "{{ home }}/Pictures"

  - name: Create the admin group and join the user to it
    command: groupadd admin && adduser "{{ user }}" admin
    become: yes
    become_method: sudo

  - name: Configure sudoers to have nopasswd use of sudo for admin group
    lineinfile:
      path: /etc/sudoers
      line: "{{ item }}"
      state: present
    with_items:
      - "# Members of the admin group may gain root privileges without pass"
      - "%admin ALL=(ALL) NOPASSWD:ALL"
    become: yes
    become_method: sudo

  - name: Get the bash and vim files from my repo for these
    command: git init && git remote add origin 'https://github.com/jadesrochers/shell_vim_config.git'

  - name: Get the bash and vim files from my repo for these
    command: git fetch && git checkout origin/master -ft

  - name: Add configuration to make the default editor vim
    lineinfile:
      path: "{{ home }}/.bashrc"
      line: "{{ item }}"
      state: present
    with_items:
      - 'export VISUAL=vim'
      - 'export EDITOR="$VISUAL"'

  - name: Change the keyboard map so caps lock is control
    command: setxkbmap -option ctrl:nocaps

  - name: Install fzf fuzzy finder. Should add its own line to .bashrc.
    command: "{{ home }}/.fzf/install"

  - name: Add a default keyboard file at /etc/default/keyboard
    copy:
      src: keyboard
      force: yes
      dest: /etc/default
    become: yes
    become_method: sudo

  - name: Add the .bashrc and .bash_profile
    copy:
      src: "{{ item }}"
      force: yes
      dest: "{{ home }}"
    with_fileglob:
       - roles/bash/files/.bash*
    become: yes
    become_method: sudo

  - name: Add .vimrc to ~/
    copy:
      src: .vimrc
      force: yes
      dest: "{{ home }}"

  - name: Source the .bashrc to finish up this part of config
    command: source ~/.bashrc
