---

  - name: Get nvm installer and pass it to shell
    shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash

  # MUST use bash as regular user to source nvm
  - name: install a recent node version, bundles npm with it.
    shell: bash -ic "nvm install {{ node_version }}"

  - name: Set this node version as default when all shells start
    shell: bash -ic "nvm alias default {{ node_version }}"

  # These will be installed globally for this user
  - name: Set this node version as default when all shells start
    shell: bash -ic "npm install --global {{ item }}"
    with_items: "{{ node_globals }}"

