---
  - name: Get the repos to install
    include_vars: repolist.yml

  - name: Clone all public and private packages I want for dev
    git:
      clone: yes
      repo: "{{ item.repo }}"
      dest: "{{ item.dest }}"
    with_items: "{{ install }}"
