---

  - name: Copy the script to download/update all vim git packages.
    copy:
      src: vimplug_update.sh
      force: yes
      dest: "{{ home }}"

  - name: Run the vimplug_update script to install plugins.
    shell: bash -ic "vimplug_update.sh"

  - name: Set the path for fzf, which I install in $HOME earlier in setup.
    lineinfile:
      path: "{{ home }}/.vimrc"
      line: "{{ item }}"
      state: present
    with_items:
      - '" fzf was installed separately, put on path'
      - set rtp+=~/.fzf

  - name: Install the compile portion of YouCompleteMe
    shell: "{{ home }}/.vim/pack/codesyntax/start/youcompleteme/install.py

