---
  - name: determine if coc.nvim is already present
    stat:
      path: "{{ home }}/.vim/pack/coc/start/coc.nvim-release"
    register: nviminstall

  - name: Make sure coc.nvim directory exists
    file:
      path: "{{ home }}/.vim/pack/coc/start"
      state: directory
      mode: 0755

  - name: output from state of coc.nvim
    debug: 
      var: nviminstall

  - name: download and unpack the coc.nvim extension
    shell: "curl --fail -L https://github.com/neoclide/coc.nvim/archive/release.tar.gz|tar xzfv -"
    args:
      chdir: "{{ home }}/.vim/pack/coc/start"
    when: nviminstall.stat.exists == false

  - name: Copy the script to download/update all vim git packages.
    copy:
      src: vimplug_update.sh
      force: yes
      dest: "{{ home }}"
      mode: 0754

  - name: Run the vimplug_update script to install plugins.
    shell: bash -ic {{ home }}/vimplug_update.sh

  - name: Set the path for fzf, which I install in $HOME earlier in setup.
    lineinfile:
      path: "{{ home }}/.vimrc"
      line: "{{ item }}"
      state: present
    with_items:
      - '" fzf was installed separately, put on path'
      - set rtp+=~/.fzf

